name        : xorg-driver-video-vesa
version     : 2.3.4
release     : 9
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-video-vesa-2.3.4.tar.gz : e7d88c014b2e93afcee4d48495f5fb69f6e03818b1f67d20a71739c190c4fb8e
license     :
    - MIT
summary     : Generic VESA video driver
component   : xorg.driver
builddeps   :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize    : no-bind-now
description : |
    The Xorg VESA Driver contains the Generic VESA video driver for the Xorg X server. This driver is often used as fallback driver if the hardware specific driver fails to load or is not present. If this driver is not installed, Xorg Server will print a warning on startup, but it can be safely ignored if hardware specific driver works well.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
