name       : xorg-driver-video-vesa
version    : 2.5.0
release    : 30
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-vesa-2.5.0.tar.gz : be10771dbfdec9e8c4f1b56653b0e6b05b3e5f79c26507e3184ad27b4f00c09d
license    : MIT
summary    : Generic VESA video driver
component  : xorg.driver
description: |
    The Xorg VESA Driver contains the Generic VESA video driver for the Xorg X server. This driver is often used as fallback driver if the hardware specific driver fails to load or is not present. If this driver is not installed, Xorg Server will print a warning on startup, but it can be safely ignored if hardware specific driver works well.
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
