name       : xorg-driver-video-vesa
version    : 2.4.0
release    : 26
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-vesa-2.4.0.tar.gz : 2982dd4eaf649101bd2c0dde37151a65157f6cbe120a692e6a6de764e36e03ea
license    :
    - MIT
summary    : Generic VESA video driver
component  : xorg.driver
description: |
    The Xorg VESA Driver contains the Generic VESA video driver for the Xorg
    X server. This driver is often used as fallback driver if the hardware
    specific driver fails to load or is not present. If this driver is not
    installed, Xorg Server will print a warning on startup, but it can be
    safely ignored if hardware specific driver works well.
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
